version: '2'
services:
  api:
    container_name: doubtfire-api
    build: .
    ports:
      - "3000:3000"
    links:
      - web
    depends_on:
      - db
    environment:
      DATABASE_URL: 'postgresql://itig:d872$$dh@db:5432/doubtfire_dev'
      RAILS_ENV: 'development'

  db:
    container_name: doubtfire-db
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: d872$$dh
      POSTGRES_USER: itig

  web:
    container_name: doubtfire-web
    build: ../doubtfire-web
    command: npm start
    environment:
      DF_DOCKER_MACHINE_IP: $DF_DOCKER_MACHINE_IP
    ports:
      - "8000:8000"
      - "8080:8080"
