name: create-doubtfire-deployment
on:
  push:
    tags:
      - 'v*'
    branch:
      - 'development'
      - 'main'
  deployment:
  workflow_dispatch:
jobs:
  docker-api-server:
    environment: doubtfire
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        if: github.event_name != 'pull_request'
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Setup meta for api server
        id: docker_meta
        uses: docker/metadata-action@v3
        with:
          images: lmsdoubtfire/apiServer
          tags: |
            type=ref,event=tag
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
      - name: Build and push api server
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: deployApi.Dockerfile
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  docker-app-server:
    environment: deployment-secrets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        if: github.event_name != 'pull_request'
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Setup meta for app server
        id: docker_meta
        uses: docker/metadata-action@v3
        with:
          images: lmsdoubtfire/appServer
          tags: |
            type=ref,event=tag
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
      - name: Build and push app server
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          file: deployAppSvr.Dockerfile
          context: .
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: ${{ github.event_name != 'pull_request' }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
